import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.book': 'Book a Table',
    'nav.menu': 'Menu',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.reservations': 'Reservations',
    'dashboard.show_reservations': 'Show Reservations',
    'dashboard.hide_reservations': 'Hide Reservations',
    'nav.tables': 'Tables',
    'nav.customers': 'Customers',
    'dashboard.customers_list': 'Customers List',
    'nav.customer_stats': 'Customer Insights',
    'customers.add': 'Add Customer',
    'customers.save_as_customer': 'Save as Customer',
    'customers.save_as_customer_success': 'Customer saved successfully!',
    'customers.customer_exists': 'Customer already exists!',
    'customers.edit_details': 'Edit Customer Details',
    'customers.update_success': 'Customer details updated successfully!',
    'customers.delete_title': 'Delete Customer?',
    'customers.delete_confirm': 'Are you sure you want to delete this customer? This action cannot be undone.',
    'nav.live_view': 'Live View',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.website': 'Website',
    'nav.language': 'Language',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.my_bookings': 'My Bookings',
    'common.add': 'Add',
    'common.today': 'Today',
    'common.day': 'Day',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.search': 'Search by name or phone...',
    'common.selected': 'Selected',
    'common.select_all': 'Select All',
    'common.deselect_all': 'Deselect All',
    'common.description': 'Description',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.exit': 'Exit',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.seats': 'seats',
    'common.remove': 'Remove',
    'profile.title': 'My Information',
    'profile.desc': 'Manage your personal details for faster bookings.',
    'profile.save_success': 'Profile updated successfully!',
    'profile.save_error': 'Error updating profile.',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'OR',
    'common.placeholder_name': 'John Doe',
    'common.verification_code': 'Verification Code',
    'common.send_code': 'Send Code',
    'common.verify_code': 'Verify Code',
    'common.phone_verified': 'Phone Verified',
    'common.invalid_code': 'Invalid verification code. Please try again.',
    'common.code_sent': 'Verification code sent successfully!',
    'common.placeholder_phone': '+1 (555) 000-0000',
    'common.placeholder_email': 'john@example.com',
    'common.placeholder_notes': 'Special requests, allergies, etc.',
    'common.guests': 'Guests',
    'common.table': 'Table',
    'common.status': 'Status',
    'common.lunch': 'Lunch',
    'common.dinner': 'Dinner',
    'common.general': 'General',
    'common.default': 'General',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.add_user': 'Add User',
    'common.new_user': 'New User',
    'common.edit_user': 'Edit User',
    'common.role': 'Role',
    'common.staff': 'Staff',
    'common.admin': 'Admin',
    'common.notes': 'Notes',
    'common.optional': 'Optional',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'common.email': 'Email',
    'common.customer': 'CUSTOMER',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.password': 'Password',
    'common.confirm_password': 'Confirm Password',
    'common.new_password': 'New Password',
    'common.confirm_new_password': 'Confirm New Password',
    'common.password_mismatch': 'Passwords do not match!',
    'common.change_password': 'Change Password',
    'users.delete_title': 'Delete User',
    'users.delete_confirm': 'Are you sure you want to remove this user? They will no longer have access to the dashboard.',
    'common.actions': 'Actions',
    'common.visits': 'Visits',
    'common.last_visit': 'Last Visit',
    'common.no_shows': 'No Shows',
    'common.no_search_results': 'No search results found.',
    'common.cancellations': 'Cancellations',
    'common.showing': 'Showing',
    'common.of': 'of',
    'common.entries': 'entries',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.page': 'Page',
    'common.rotation': 'Rotation',
    'common.shape': 'Shape',
    'common.round': 'Round',
    'common.square': 'Square',
    'common.rectangle': 'Rectangle',
    'res.book_table': 'Book a Table',
    'res.book_success': 'The reservation was saved successfully.',
    'res.new': 'New Reservation',
    'res.new_reservation': 'New Reservation',
    'res.edit': 'Edit Reservation',
    'res.delete_title': 'Delete Reservation?',
    'res.delete_confirm': 'Are you sure you want to cancel and remove this reservation? This action cannot be undone.',
    'res.keep': 'Keep it',
    'res.no_bookings': 'No bookings',
    'res.no_bookings_yet': "You haven't made any reservations yet.",
    'res.no_res_found': 'No reservations found for this date.',
    'res.pending': 'Pending',
    'res.booked': 'Booked',
    'res.confirmed': 'Confirmed',
    'res.arrived': 'Already In',
    'res.no_show': 'No Show',
    'res.no-show': 'No Show',
    'res.cancelled': 'Cancelled',
    'res.completed': 'Completed',
    'res.waiting-list': 'Waiting List',
    'res.delayed': 'Delayed',
    'res.restore_selected': 'Restore Selected',
    'res.delete_selected': 'Delete Selected',
    'res.delete_selected_title': 'Delete Selected Reservations?',
    'res.delete_selected_desc': 'Are you sure you want to permanently delete these reservations? This action cannot be undone.',
    'res.no_table': 'No Table',
    'res.unassigned': 'Unassigned',
    'res.cancel': 'Cancel Reservation',
    'res.cancel_success': 'Reservation cancelled successfully.',
    'res.cancel_error': 'Error cancelling reservation.',
    'res.delete_forever': 'Are you sure you want to delete this data?',
    'res.data_history_delete_title': 'Are you sure you want to permanently delete this data?',
    'res.data_history_delete_desc': 'This action cannot be undone. Once deleted, this data will be permanently removed and cannot be recovered.',
    'res.delete_forever_desc': 'Deleted data can only be recovered by an administrator with data recovery access.',
    'res.delete_success': 'Reservation deleted successfully!',
    'res.unjoin_warning': 'Unjoin Warning',
    'res.no_table_assigned': 'has no suitable table assigned anymore.',
    'res.increase_window': 'Increase Window',
    'res.decrease_window': 'Decrease Window',
    'tables.editor': 'Floor Plan Editor',
    'tables.drag_drop': 'Drag and drop tables to arrange your restaurant layout.',
    'tables.add': 'Add Table',
    'tables.new': 'Add New Table',
    'tables.edit': 'Edit Table',
    'tables.delete_title': 'Delete Table?',
    'tables.delete_confirm': 'Are you sure you want to remove this table from the floor plan?',
    'tables.name_ref': 'Table Name/Reference',
    'tables.seats': 'Number of Seats',
    'tables.create': 'Create Table',
    'tables.available': 'Available',
    'tables.reserved': 'Reserved',
    'tables.occupied': 'Occupied',
    'tables.no_tables': 'No tables added yet.',
    'tables.click_add': 'Click "Add Table" to start building your floor plan.',
    'tables.allow_online': 'Allow Online Reservations',
    'tables.allow_online_desc': 'Enable this to allow clients to book this table online. Turn off for staff-only bookings.',
    'tables.default_layout': 'Default Layout',
    'tables.lunch_layout': 'Lunch Layout',
    'tables.dinner_layout': 'Dinner Layout',
    'settings.title': 'App Settings',
    'settings.desc': 'Configure your app settings and branding.',
    'settings.basic': 'Restaurant Information',
    'settings.rest_name': 'Restaurant Name',
    'settings.website': 'Website URL',
    'settings.address': 'Address',
    'settings.contact': 'Contact Details',
    'settings.branding': 'Branding & Assets',
    'settings.website_customization': 'Website Customization',
    'settings.enable_page_transitions': 'Enable Page Transitions',
    'settings.enable_page_transitions_desc': 'Smooth animations between pages',
    'settings.font_family': 'Font Family',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.hero_height': 'Hero Section Set Height',
    'settings.brand_color': 'Brand Primary Color',
    'settings.button_radius': 'Button Border Radius',
    'settings.box_radius': 'Box Border Radius',
    'settings.input_radius': 'Input Border Radius',
    'settings.radius_none': 'None',
    'settings.radius_sm': 'Small',
    'settings.radius_md': 'Medium',
    'settings.radius_lg': 'Large',
    'settings.radius_xl': 'Extra Large',
    'settings.radius_2xl': 'XX-Large',
    'settings.radius_full': 'Full',
    'settings.compact': 'Compact',
    'settings.standard': 'Standard',
    'settings.full_screen': 'Full Screen',
    'settings.logo': 'Logo URL',
    'settings.logo_size': 'Logo Display Height',
    'settings.logo_size_desc': 'Adjust the height of the logo across the website',
    'settings.favicon': 'Favicon (Browser Tab Icon)',
    'settings.favicon_desc': 'Upload or enter a dedicated favicon image (.ico, .png, .svg, .jpg, .webp). If set, this image is used as the browser tab icon; otherwise the default favicon is used.',
    'settings.favicon_preview': 'Favicon Preview',
    'settings.favicon_default': 'Default Favicon Active',
    'settings.favicon_custom': 'Dedicated Favicon Active',
    'settings.favicon_clear': 'Default',
    'settings.default_btn': 'Default',
    'settings.show_logo': 'Show Logo',
    'settings.show_logo_desc': 'Display the logo image in the header and footer',
    'settings.show_name': 'Show Restaurant Name',
    'settings.show_name_desc': 'Display the restaurant name text next to or in place of the logo',
    'settings.hero': 'Hero Image URL',
    'settings.hero_overlay': 'Hero Overlay',
    'settings.intensity': 'Intensity',
    'settings.bin': 'Recycle Bin',
    'settings.bin_empty': 'Your recycling bin is empty',
    'settings.data_history': 'Data History',
    'settings.all_data': 'All Data',
    'settings.data_history_access': 'Data History Access',
    'settings.data_history_access_desc': 'Please enter the Data History password to access permanently deleted records.',
    'settings.enter_password': 'Enter password',
    'settings.access': 'Access',
    'settings.back_to_bin': 'Back to Bin',
    'settings.allow_online': 'Allow Online Reservations',
    'settings.phone_verification': 'SMS Phone Verification',
    'settings.phone_verification_desc': 'Require customers to verify their phone number via SMS OTP code using Twilio before completing an online booking. Ensure your Twilio credentials are correct below.',
    'settings.allow_online_desc': 'If off, customers will see a message to call instead of the booking form.',
    'settings.max_online_guests': 'Maximum Guests for Online Booking',
    'settings.max_online_guests_desc': 'The maximum number of guests a customer can book online. For larger groups, they will be prompted to contact the restaurant.',
    'settings.max_months_ahead': 'Online Booking Period (Months)',
    'settings.max_months_ahead_desc': 'How many months ahead customers can book online (e.g., 1, 2, 3 months).',
    'settings.show_insights': 'Show Customer Insights',
    'settings.show_insights_desc': 'Enable a detailed page with customer visit statistics for administrators.',
    'settings.cloudinary': 'Cloudinary Configuration',
    'settings.cloudinary_cloud_name': 'Cloud Name',
    'settings.cloudinary_api_key': 'API Key',
    'settings.cloudinary_api_secret': 'API Secret',
    'settings.cloudinary_upload_preset': 'Upload Preset',
    'settings.use_cloudinary': 'Use Cloudinary',
    'settings.use_cloudinary_desc': 'If enabled, the app will prioritize images from Cloudinary.',
    'settings.upload_to_cloudinary': 'Upload to Cloudinary',
    'settings.seo': 'Restaurant SEO',
    'settings.seo_desc': 'Improve how your restaurant appears on Google and other search engines.',
    'settings.seo_health_score': 'SEO Health Score',
    'settings.seo_sync_details': 'Auto-fill from Restaurant Details',
    'settings.seo_sync_success': 'SEO fields populated from restaurant profile!',
    'settings.seo_basic_title': 'Basic SEO Information',
    'settings.seo_basic_desc': 'The primary title and meta description displayed on search engine result pages (SERPs).',
    'settings.seo_title': 'SEO Title',
    'settings.seo_title_desc': 'The title shown by search engines for your restaurant page.',
    'settings.seo_title_placeholder': 'Restaurant Name | Restaurant Type | City',
    'settings.seo_meta_desc': 'Meta Description',
    'settings.seo_meta_desc_desc': 'A short description that appears in search results below your title.',
    'settings.seo_meta_desc_placeholder': 'Experience fine dining with authentic flavors and exceptional service. Book your table online today.',
    'settings.seo_keywords': 'Keywords / Search Terms',
    'settings.seo_keywords_desc': 'Comma-separated keywords or key phrases related to your restaurant.',
    'settings.seo_keywords_placeholder': 'restaurant, seafood, fine dining, outdoor seating, city name',
    'settings.seo_site_name': 'Website / Brand Name (og:site_name)',
    'settings.seo_site_name_desc': 'The overall brand or website name displayed in OpenGraph tags (defaults to your restaurant name).',
    'settings.seo_site_name_placeholder': 'e.g. Bella Vista Fine Dining',
    'settings.seo_og_url': 'Canonical / Open Graph URL (og:url)',
    'settings.seo_og_url_desc': 'The primary canonical URL for search indexing and social sharing link tags.',
    'settings.seo_og_url_placeholder': 'https://your-restaurant-domain.com/',
    'settings.seo_local_title': 'Local SEO & Rich Snippets',
    'settings.seo_local_desc': 'Business information helping search engines display your restaurant in local map packs and rich cards.',
    'settings.seo_cuisine_type': 'Cuisine / Restaurant Type',
    'settings.seo_cuisine_placeholder': 'e.g. Traditional Portuguese, Seafood, Mediterranean, Grill',
    'settings.seo_price_range': 'Price Range',
    'settings.seo_city': 'City / Town',
    'settings.seo_state': 'State / County / Region',
    'settings.seo_postal_code': 'Postal / ZIP Code',
    'settings.seo_country': 'Country',
    'settings.seo_address': 'Street Address for SEO',
    'settings.seo_google_business': 'Google Business Profile URL',
    'settings.seo_google_maps': 'Google Maps Place URL',
    'settings.seo_latitude': 'Latitude',
    'settings.seo_longitude': 'Longitude',
    'settings.seo_geo_hint': 'Coordinates help search engines accurately pin your restaurant on map searches.',
    'settings.seo_social_title': 'Social Sharing (Open Graph & Twitter)',
    'settings.seo_social_desc': 'Control how your restaurant link appears when shared on WhatsApp, Facebook, Instagram, LinkedIn, and Twitter/X.',
    'settings.seo_social_share_title': 'Social Sharing Title',
    'settings.seo_social_share_title_hint': 'Leave empty to automatically use your SEO Title',
    'settings.seo_social_share_desc': 'Social Sharing Description',
    'settings.seo_social_share_desc_hint': 'Leave empty to automatically use your Meta Description',
    'settings.seo_social_image': 'Social Share Image (1200 × 630 px)',
    'settings.seo_social_image_desc': 'Recommended aspect ratio 1.91:1 (1200x630px). Enter a manual image URL or upload to Cloudinary. If no image URL is provided, no image will be displayed in social previews or search share cards.',
    'settings.seo_social_image_clear': 'Clear Image',
    'settings.seo_social_no_image': 'No social image specified. No image will be displayed when sharing links.',
    'settings.seo_social_image_active': 'Social Image Active',
    'settings.seo_social_image_none': 'No Image (Text-Only Card)',
    'settings.seo_preview_title': 'Search Engine & Social Previews',
    'settings.seo_google_preview': 'Google Search SERP Preview',
    'settings.seo_social_preview': 'Social Sharing Preview',
    'settings.seo_social_box_bg_color': 'Preview Box Background Color',
    'settings.seo_social_box_bg_color_desc': 'Customize the bottom info box background color in this preview card simulator.',
    'settings.seo_social_box_bg_disclaimer': 'Admin Preview Only: This is only a design preference for this preview simulator. Third-party platforms (WhatsApp, Facebook, Twitter/X, etc.) render links according to their own native design and color schemes.',
    'settings.seo_social_box_bg_reset': 'Reset Box Background',
    'settings.seo_social_box_bg_custom': 'Custom Box Color',
    'settings.seo_social_box_bg_default': 'Default System Style',
    'settings.seo_desktop_view': 'Desktop',
    'settings.seo_mobile_view': 'Mobile',
    'settings.seo_recommendations': 'Actionable SEO Recommendations',
    'settings.seo_advanced_title': 'Indexing & Structured Data',
    'settings.seo_indexing_toggle': 'Allow search engines to index this site',
    'settings.seo_indexing_on_desc': 'Search engines (Google, Bing, etc.) are allowed to index and rank your pages.',
    'settings.seo_indexing_off_desc': '⚠️ "noindex, nofollow" will be applied. Your restaurant page will be hidden from search engines.',
    'settings.seo_canonical_url': 'Custom Canonical URL',
    'settings.seo_canonical_desc': 'Specify the preferred URL for this page to prevent duplicate content issues. Auto-generated if blank.',
    'settings.seo_jsonld_title': 'Restaurant Structured Data (Schema.org JSON-LD)',
    'settings.seo_jsonld_desc': 'Automatically generated machine-readable data helping Google generate rich cards, opening hours, star ratings, and reservation actions.',
    'settings.seo_copy_jsonld': 'Copy JSON-LD',
    'settings.seo_jsonld_copied': 'JSON-LD copied to clipboard!',
    'settings.seo_test_rich_results': 'Test with Google Rich Results',
    'settings.resend_api': 'Resend API Configuration',
    'settings.resend_api_key': 'Resend API Key',
    'settings.resend_api_desc': 'Use Resend to send transactional emails to your customers.',
    'settings.resend_from_email': 'Resend From Email',
    'settings.resend_from_email_desc': 'The verified sender email address in your Resend account (defaults to "onboarding@resend.dev"). NOTE: When using onboarding@resend.dev, you can only send emails to your own registered Resend email address. To send to other emails, you must verify your domain in Resend and enter your verified sender email here.',
    'settings.firebase_config': 'Firebase Configuration',
    'settings.firebase_api_key': 'API Key',
    'settings.firebase_auth_domain': 'Auth Domain',
    'settings.firebase_project_id': 'Project ID',
    'settings.firebase_storage_bucket': 'Storage Bucket',
    'settings.firebase_messaging_sender_id': 'Messaging Sender ID',
    'settings.firebase_app_id': 'App ID',
    'settings.firebase_measurement_id': 'Measurement ID',
    'settings.firebase_database_id': 'Database ID (optional)',
    'settings.firebase_desc': 'Configure a custom Firebase project to host your data when deploying outside this environment.',
    'settings.twilio_config': 'Twilio Configuration',
    'settings.twilio_account_sid': 'Twilio Account SID',
    'settings.twilio_auth_token': 'Twilio Auth Token',
    'settings.twilio_phone_number': 'Twilio Phone Number',
    'settings.twilio_desc': 'Configure your Twilio account to send real SMS verification codes for reservation security. If not configured, the application will fallback to simulated console log messages.',
    'settings.call_now': 'Call now to book a table',
    'settings.call_only_desc': 'We are currently only accepting reservations via phone. Please contact us directly to secure your table.',
    'settings.interval': 'Reservation Interval (min)',
    'settings.interval_desc': 'This interval applies to all standard opening hours.',
    'settings.freeze_app': 'Freeze App (Auto-Lock)',
    'settings.freeze_desc': 'When enabled, the application will lock after a period of inactivity. Useful for shared tablets or front-of-house security.',
    'settings.freeze_pass': 'Unfreeze Password',
    'settings.freeze_time': 'Inactivity Timeout (minutes)',
    'settings.freeze_on': 'Freeze Enabled',
    'settings.min_gap': 'Min. Gap Between Bookings (min)',
    'settings.min_gap_desc': 'Minimum time required between reservations on the same table.',
    'settings.default_gap': 'Default Gap',
    'login.title': 'Welcome Back',
    'login.desc': 'Choose how you want to sign in to your account.',
    'login.staff': 'Staff Login',
    'login.staff_desc': 'Access the dashboard and manage the restaurant.',
    'login.customer': 'Customer Login',
    'login.customer_desc': 'Manage your bookings and profile.',
    'login.signup_title': 'Create Account',
    'login.signup_desc': 'Join us to manage your reservations and get exclusive offers.',
    'login.google': 'Sign in with Google',
    'login.google_signup': 'Sign up with Google',
    'login.no_account': "Don't have an account? Sign up",
    'login.have_account': 'Already have an account? Log in',
    'settings.special_days': 'Special Days Configuration',
    'settings.add_special': 'Add Special Day',
    'settings.footer': 'Footer Image URL',
    'settings.footer_overlay': 'Footer Overlay',
    'settings.hours': 'Opening Hours',
    'settings.social': 'Social Media Links',
    'settings.add_social': 'Add Social Link',
    'settings.platform': 'Platform',
    'settings.url': 'URL',
    'settings.closed': 'Closed',
    'settings.open': 'Open',
    'settings.close': 'Close',
    'settings.closed_days': 'Closed Days',
    'settings.specific_closed': 'Specific Closed Days (Holidays, etc.)',
    'settings.closed_periods': 'Closed Periods (Vacations, etc.)',
    'settings.add_period': 'Add Period',
    'settings.start_date': 'Start Date',
    'settings.end_date': 'End Date',
    'settings.period_note': 'Note (e.g. Easter Holidays)',
    'settings.recurring_yearly': 'Mark as Always (Recurring Yearly)',
    'settings.message_popup': 'Message Popup',
    'settings.promo_active': 'Active',
    'settings.promo_start': 'Start Date',
    'settings.promo_end': 'End Date',
    'settings.promo_title': 'Title',
    'settings.promo_subtitle': 'Subtitle',
    'settings.promo_message': 'Message',
    'settings.tripadvisor_widget': 'TripAdvisor Reviews Widget',
    'settings.tripadvisor_desc': 'Paste your TripAdvisor widget embed code below',
    'settings.tripadvisor_note': 'Note: This widget will be displayed on the public "Book a Table" page.',
    'settings.google_maps_widget': 'Google Maps Widget',
    'settings.google_maps_desc': 'Paste your Google Maps embed code below',
    'settings.google_maps_note': 'Note: This widget will be displayed on the footer of the public "Book a Table" page.',
    'dashboard.welcome': 'Welcome back! Here\'s what\'s happening today.',
    'dashboard.welcome_back': 'Welcome back,',
    'dashboard.welcome_today': ' Here\'s what\'s happening today.',
    'dashboard.manage_bookings_desc': 'View and manage your upcoming and past reservations.',
    'dashboard.past_cancelled': 'Past & Cancelled Reservations',
    'dashboard.today_res': 'Today\'s Reservations',
    'dashboard.pending': 'Pending Requests',
    'dashboard.available_tables': 'Available Tables',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.live_status': 'Real-time floor plan status',
    'dashboard.upcoming': 'Upcoming & Active',
    'dashboard.legend': 'Legend',
    'dashboard.upcoming_reports': 'Upcoming Bookings',
    'dashboard.upcoming_reports_desc': 'Interactive summary of future reservations by date',
    'dashboard.no_upcoming_reports': 'No upcoming bookings to report.',
    'dashboard.reset_hidden': 'Reset Hidden',
    'dashboard.show_hidden': 'Show Hidden Dates',
    'dashboard.remove_report_confirm': 'Are you sure you want to remove this reservation report from this section? This will not cancel the actual reservations.',
    'settings.show_live_upcoming': 'Upcoming & Active List',
    'settings.show_live_upcoming_desc': 'Show current service bookings on Live View',
    'settings.show_lang_switch': 'Show Language Toggle',
    'settings.show_lang_switch_desc': 'Show PT/EN language switcher in the navigation bar',
    'settings.silent_bell': 'Silent Bell (Notifications)',
    'settings.silent_bell_desc': 'Silence the sound chime when a new public order/booking comes in',
    'settings.description_pt': 'Description (PT)',
    'settings.description_en': 'Description (EN)',
    'settings.time_format': 'Time Format',
    'settings.time_format_desc': 'Choose how time is displayed across the application (AM/PM or 24-hour format).',
    'settings.floor_plan_title': 'Floor Plan Layout Background',
    'settings.floor_plan_show': 'Show Floor Plan Background Image',
    'settings.floor_plan_show_desc': 'Display an image layout of your room behind the table grids.',
    'settings.floor_plan_url': 'Floor Plan Image URL',
    'settings.floor_plan_url_desc': 'Provide a URL for the floor plan background, or leave blank to use the default Nortada Sala Plan.',
    'settings.floor_plan_opacity': 'Floor Plan Overlay Intensity',
    'settings.floor_plan_bg_type': 'Background Source',
    'settings.floor_plan_bg_type_desc': 'Choose whether to display your uploaded custom floor plan or the default room layout.',
    'settings.floor_plan_use_default': 'Use Default Room Layout',
    'settings.floor_plan_use_custom': 'Use Uploaded Custom Floor Plan',
    'res.auto_assign': 'Auto-assign Table',
    'res.no_table_assign': 'No Table Assignment',
    'public.book_title': 'Book Your Table',
    'public.login_manage': 'Sign up or Login to manage your bookings! or Book as a guest',
    'public.book_desc': 'Experience fine dining at its best. Reserve your spot today.',
    'public.hero_subtitle': 'Experience fine dining at its best. Reserve your spot today.',
    'public.experience_fine_dining': 'Experience fine dining at its best. Reserve your spot today, at {name}.',
    'public.reviews_tripadvisor': 'What our guests say on TripAdvisor',
    'public.select_date': 'Select Date',
    'public.guest_info': 'Guest Information',
    'public.confirm_booking': 'Confirm Booking',
    'public.success_title': 'Reservation Confirmed!',
    'public.success_desc': 'We look forward to seeing you.',
    'public.closed_message': 'We are closed on this day. Please select another date.',
    'public.closed_period_message': 'We are closed for {reason}. We will be back on {date}.',
    'public.back_on': 'Back on',
    'public.large_group_note': 'For reservation over {max} guests, please contact us directly for availability.',
    'auth.logged_in_as': 'Logged in as',
    'auth.login_success': 'Login successful',
    'auth.logged_out': 'Logged out successfully',
    'auth.login_error': 'Error logging in',
    'auth.invalid_credentials': 'Invalid email or password. Please try again.',
    'auth.email_in_use': 'This email is already registered. Please try logging in instead.',
    'auth.logout_error': 'Error logging out',
    'auth.verify_email_sent': 'Verification email sent! Please check your inbox.',
    'auth.verify_email_first': 'Please verify your email before logging in.',
    'common.all_rights_reserved': 'All rights reserved.',
    'common.privacy_policy': 'Privacy Policy',
    'common.terms_conditions': 'Terms & Conditions',
    'common.cookie_policy': 'Cookie Policy',
    'common.quick_links': 'Quick Links',
    'common.opening_hours': 'Opening Hours',
    'common.open': 'Open',
    'common.close': 'Close',
    'common.to': 'to',
    'common.closed': 'Closed',
    'common.saving': 'Saving...',
    'common.save_success': 'Settings saved successfully!',
    'common.save_error': 'Error saving settings.',
    'common.cookie_consent': 'We use cookies to improve your experience on our website.',
    'common.cookie_accept': 'Accept',
    'common.cookie_decline': 'Decline',
    'common.access_denied': 'Access Denied.',
    'common.account_suspended': 'Your account is currently unavailable.',
    'common.you': 'You',
    'common.address': 'Address',
    'common.localization': 'Localization',
    'common.no_messages': 'No messages created yet.',
    'common.create_first': 'Create your first message',
    'common.image_url': 'Image URL',
    'common.yearly_recurring': 'Yearly Recurring',
    'common.general_hours': 'General Hours',
    'common.start_date': 'Start Date',
    'common.end_date': 'End Date',
    'res.full_house_on': 'Full House ON',
    'res.full_house_off': 'Full House OFF',
    'res.full_house_msg_active': 'Full House Mode Active for this Date',
    'res.full_house_msg_deactive': 'Full House Mode Deactivated for this Date',
    'res.full_house_lunch_active': 'Full House Mode Active for Lunch',
    'res.full_house_lunch_deactive': 'Full House Mode Deactivated for Lunch',
    'res.full_house_dinner_active': 'Full House Mode Active for Dinner',
    'res.full_house_dinner_deactive': 'Full House Mode Deactivated for Dinner',
    'res.lunch_full': 'LUNCH FULL',
    'res.lunch_open': 'LUNCH OPEN',
    'res.dinner_full': 'DINNER FULL',
    'res.dinner_open': 'DINNER OPEN',
    'dashboard.manage_customers': 'View and manage your customer database.',
    'dashboard.manage_staff': 'Manage staff access and roles.',
    'dashboard.floor_plan': 'Drag and drop tables to arrange your restaurant layout.',
    'res.add_table_hint': 'Click "Add Table" to start building your floor plan.',
    'res.no_tables': 'No tables added yet.',
    'res.available': 'Available',
    'res.reserved': 'Reserved',
    'res.occupied': 'Occupied',
    'res.conflict_title': 'Time Conflict!',
    'res.conflict_desc': 'This assignment overlaps with an existing booking for {name} at {time}. The required gap between bookings is {gap}.',
    'res.assign_anyway': 'Assign Anyway',
    'res.manage_seatings': 'Manage Seatings',
    'res.mark_fully_booked': 'Mark as Fully Booked',
    'res.seating': 'Seating',
    'res.add_second_seating': 'Add Second Seating (Auto-calculated)',
    'res.done': 'Done',
    'res.change_time': 'Change Time',
    'res.walkin': 'Quick Walk-in',
    'res.walkin_confirm': 'Confirm Walk-in',
    'res.set_now': 'Set to Now',
    'tables.join': 'Join Tables',
    'tables.join_desc': 'Select tables to join side-by-side.',
    'tables.total_seats': 'Total Seats when Joined',
    'tables.unjoin': 'Unjoin All',
    'res.waitlist': 'Waiting List',
    'res.show_waitlist': 'Waitlist',
    'res.full_house': 'No online availability',
    'res.full_house_desc': 'We currently cannot accept more online bookings. Please contact us directly for availability.',
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',
    'days.mon': 'Mon',
    'days.tue': 'Tue',
    'days.wed': 'Wed',
    'days.thu': 'Thu',
    'days.fri': 'Fri',
    'days.sat': 'Sat',
    'days.sun': 'Sun',
    'captcha.verify': 'I am not a robot',
    'captcha.required': 'Please verify that you are not a robot.',
    'captcha.robot_alert': 'Please complete the verification check before booking.',
    'captcha.loading': 'Verifying...',
    'settings.grace_period': 'Reservation Grace Period (Minutes)',
    'settings.grace_period_desc': 'Specify the tolerance time (in minutes) allowed for late guest arrivals before a reservation is considered expired and the table is released.',
    'settings.enable_booking_number': 'Generate Unique Booking Number',
    'settings.enable_booking_number_desc': 'Generate a unique booking code (e.g., RES-2026-00001) for every new reservation.',
    'notfound.badge': '404 Error',
    'notfound.title': 'Page Not Found',
    'notfound.desc': 'The page you are looking for does not exist, has been moved, or the link is broken.',
    'notfound.back_home': 'Return to Home',
    'notfound.book_table': 'Book a Table',
    'notfound.go_back': 'Go Back',
    'notfound.admin_dashboard': 'Admin Dashboard',
    'notfound.my_bookings': 'My Bookings',
    'notfound.need_help': 'Need assistance?',
    'notfound.contact_us': 'Contact us directly',
  },
  pt: {
    'nav.book': 'Reservar Mesa',
    'nav.menu': 'Menu',
    'nav.about': 'Sobre Nós',
    'nav.contact': 'Contacto',
    'nav.dashboard': 'Painel',
    'nav.reservations': 'Reservas',
    'dashboard.show_reservations': 'Mostrar Reservas',
    'dashboard.hide_reservations': 'Ocultar Reservas',
    'nav.tables': 'Mesas',
    'nav.customers': 'Clientes',
    'dashboard.customers_list': 'Lista de Clientes',
    'nav.customer_stats': 'Estatísticas de Clientes',
    'customers.add': 'Adicionar Cliente',
    'customers.save_as_customer': 'Guardar como Cliente',
    'customers.save_as_customer_success': 'Cliente guardado com sucesso!',
    'customers.customer_exists': 'O cliente já existe!',
    'customers.edit_details': 'Editar Detalhes do Cliente',
    'customers.update_success': 'Detalhes do cliente atualizados com sucesso!',
    'customers.delete_title': 'Eliminar Cliente?',
    'customers.delete_confirm': 'Tem a certeza que deseja eliminar este cliente? Esta ação não pode ser desfeita.',
    'nav.live_view': 'Planta em Tempo Real',
    'nav.users': 'Utilizadores',
    'nav.settings': 'Definições',
    'nav.website': 'Website',
    'nav.language': 'Idioma',
    'nav.logout': 'Sair',
    'nav.login': 'Login',
    'nav.signup': 'Registar',
    'nav.my_bookings': 'As Minhas Reservas',
    'common.add': 'Adicionar',
    'common.today': 'Hoje',
    'common.day': 'Dia',
    'common.week': 'Semana',
    'common.month': 'Mês',
    'common.search': 'Procurar por nome ou telefone...',
    'common.selected': 'Selecionados',
    'common.select_all': 'Selecionar Tudo',
    'common.deselect_all': 'Desmarcar Tudo',
    'common.description': 'Descrição',
    'common.loading': 'A carregar...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.exit': 'Sair',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.seats': 'lugares',
    'common.remove': 'Remover',
    'profile.title': 'A Minha Informação',
    'profile.desc': 'Gira os seus dados pessoais para reservas mais rápidas.',
    'profile.save_success': 'Perfil atualizado com sucesso!',
    'profile.save_error': 'Erro ao atualizar o perfil.',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.or': 'OU',
    'common.placeholder_name': 'João Silva',
    'common.verification_code': 'Código de Verificação',
    'common.send_code': 'Enviar Código',
    'common.verify_code': 'Verificar Código',
    'common.phone_verified': 'Telefone Verificado',
    'common.invalid_code': 'Código de verificação inválido. Por favor, tente novamente.',
    'common.code_sent': 'Código de verificação enviado com sucesso!',
    'common.placeholder_phone': '+351 910 000 000',
    'common.placeholder_email': 'joao@exemplo.com',
    'common.placeholder_notes': 'Pedidos especiais, alergias, etc.',
    'common.guests': 'Pessoas',
    'common.table': 'Mesa',
    'common.status': 'Estado',
    'common.lunch': 'Almoço',
    'common.dinner': 'Jantar',
    'common.general': 'Geral',
    'common.default': 'Geral',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.add_user': 'Adicionar Utilizador',
    'common.new_user': 'Novo Utilizador',
    'common.edit_user': 'Editar Utilizador',
    'common.role': 'Função',
    'common.staff': 'Equipa',
    'common.admin': 'Administrador',
    'common.notes': 'Notas',
    'common.optional': 'Opcional',
    'common.name': 'Nome',
    'common.phone': 'Telefone',
    'common.email': 'Email',
    'common.customer': 'Cliente',
    'common.date': 'Data',
    'common.time': 'Hora',
    'common.password': 'Senha',
    'common.confirm_password': 'Confirmar Senha',
    'common.new_password': 'Nova Senha',
    'common.confirm_new_password': 'Confirmar Nova Senha',
    'common.password_mismatch': 'As senhas não coincidem!',
    'common.change_password': 'Alterar Senha',
    'users.delete_title': 'Eliminar Utilizador',
    'users.delete_confirm': 'Tem a certeza que deseja remover este utilizador? Ele deixará de ter acesso ao painel de controlo.',
    'common.actions': 'Ações',
    'common.visits': 'Visitas',
    'common.last_visit': 'Última Visita',
    'common.no_shows': 'Faltas',
    'common.no_search_results': 'Nenhum resultado encontrado.',
    'common.cancellations': 'Cancelamentos',
    'common.showing': 'A mostrar',
    'common.of': 'de',
    'common.entries': 'registos',
    'common.previous': 'Anterior',
    'common.next': 'Próximo',
    'common.page': 'Página',
    'common.rotation': 'Rotação',
    'common.shape': 'Formato',
    'common.round': 'Redonda',
    'common.square': 'Quadrada',
    'common.rectangle': 'Retangular',
    'res.book_table': 'Reservar Mesa',
    'res.book_success': 'A reserva foi guardada com sucesso.',
    'res.new': 'Nova Reserva',
    'res.new_reservation': 'Nova Reserva',
    'res.edit': 'Editar Reserva',
    'res.delete_title': 'Eliminar Reserva?',
    'res.delete_confirm': 'Tem a certeza que deseja cancelar e remover esta reserva? Esta ação não pode ser desfeita.',
    'res.keep': 'Manter',
    'res.no_bookings': 'Sem reservas',
    'res.no_bookings_yet': 'Ainda não fez nenhuma reserva.',
    'res.no_res_found': 'Nenhuma reserva encontrada para esta data.',
    'res.pending': 'Pendente',
    'res.booked': 'Reservado',
    'res.confirmed': 'Confirmada',
    'res.arrived': 'Já Chegou',
    'res.no_show': 'Não Compareceu',
    'res.no-show': 'Não Compareceu',
    'res.cancelled': 'Cancelada',
    'res.completed': 'Concluída',
    'res.waiting-list': 'Lista de Espera',
    'res.delayed': 'Atrasada',
    'res.restore_selected': 'Restaurar Selecionados',
    'res.delete_selected': 'Eliminar Selecionados',
    'res.delete_selected_title': 'Eliminar Reservas Selecionadas?',
    'res.delete_selected_desc': 'Tem a certeza que deseja eliminar permanentemente estas reservas? Esta ação não pode ser desfeita.',
    'res.no_table': 'Sem Mesa',
    'res.unassigned': 'Não Atribuída',
    'res.cancel': 'Cancelar Reserva',
    'res.cancel_success': 'Reserva cancelada com sucesso.',
    'res.cancel_error': 'Erro ao cancelar a reserva.',
    'res.delete_forever': 'Tem a certeza que pretende eliminar estes dados?',
    'res.data_history_delete_title': 'Tem a certeza de que pretende eliminar permanentemente estes dados?',
    'res.data_history_delete_desc': 'Esta ação não pode ser desfeita. Uma vez eliminados, estes dados serão removidos permanentemente e não poderão ser recuperados.',
    'res.delete_forever_desc': 'Os dados eliminados só podem ser recuperados por um administrador com acesso à recuperação de dados.',
    'res.delete_success': 'Eliminado com sucesso!',
    'res.unjoin_warning': 'Aviso de Desvinculação',
    'res.no_table_assigned': 'já não tem uma mesa adequada atribuída.',
    'res.increase_window': 'Aumentar Janela',
    'res.decrease_window': 'Reduzir Janela',
    'tables.editor': 'Editor de Planta',
    'tables.drag_drop': 'Arraste e solte as mesas para organizar o layout do seu restaurante.',
    'tables.add': 'Adicionar Mesa',
    'tables.new': 'Adicionar Nova Mesa',
    'tables.edit': 'Editar Mesa',
    'tables.delete_title': 'Eliminar Mesa?',
    'tables.delete_confirm': 'Tem a certeza que deseja remover esta mesa da planta?',
    'tables.name_ref': 'Nome/Referência da Mesa',
    'tables.seats': 'Número de Lugares',
    'tables.create': 'Criar Mesa',
    'tables.available': 'Disponível',
    'tables.reserved': 'Reservada',
    'tables.occupied': 'Ocupada',
    'tables.no_tables': 'Nenhuma mesa adicionada ainda.',
    'tables.click_add': 'Clique em "Adicionar Mesa" para começar a construir a sua planta.',
    'tables.allow_online': 'Permitir Reservas Online',
    'tables.allow_online_desc': 'Ative esta opção para permitir que os clientes reservem esta mesa online. Desative para reservas exclusivas do pessoal.',
    'tables.default_layout': 'Layout Padrão',
    'tables.lunch_layout': 'Layout de Almoço',
    'tables.dinner_layout': 'Layout de Jantar',
    'settings.title': 'Definições da App',
    'settings.desc': 'Configure as definições e a marca da sua aplicação.',
    'settings.basic': 'Informações do Restaurante',
    'settings.rest_name': 'Nome do Restaurante',
    'settings.website': 'URL do Website',
    'settings.address': 'Morada',
    'settings.contact': 'Detalhes de Contacto',
    'settings.branding': 'Marca e Visuais',
    'settings.website_customization': 'Personalização do Website',
    'settings.enable_page_transitions': 'Ativar Transições de Página',
    'settings.enable_page_transitions_desc': 'Animações suaves entre páginas',
    'settings.font_family': 'Tipo de Letra',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Escuro',
    'settings.hero_height': 'Altura da Secção Principal',
    'settings.brand_color': 'Cor Primária da Marca',
    'settings.button_radius': 'Ângulo dos cantos dos Botões',
    'settings.box_radius': 'Ângulo dos cantos das caixas',
    'settings.input_radius': 'Ângulo dos cantos dos inputs',
    'settings.radius_none': 'Nenhum',
    'settings.radius_sm': 'Pequeno',
    'settings.radius_md': 'Médio',
    'settings.radius_lg': 'Grande',
    'settings.radius_xl': 'Extra Grande',
    'settings.radius_2xl': 'Muito Grande',
    'settings.radius_full': 'Completo',
    'settings.compact': 'Compacto',
    'settings.standard': 'Padrão',
    'settings.full_screen': 'Ecrã Inteiro',
    'settings.logo': 'URL do Logótipo',
    'settings.logo_size': 'Altura de Exibição do Logótipo',
    'settings.logo_size_desc': 'Ajuste a altura do logótipo em todo o website',
    'settings.favicon': 'Favicon (Ícone do Separador do Navegador)',
    'settings.favicon_desc': 'Envie ou insira a imagem do favicon dedicado (.ico, .png, .svg, .jpg, .webp). Se preenchido, esta imagem será usada no separador do navegador; caso contrário, será usado o favicon padrão.',
    'settings.favicon_preview': 'Pré-visualização do Favicon',
    'settings.favicon_default': 'Favicon Padrão Ativo',
    'settings.favicon_custom': 'Favicon Dedicado Ativo',
    'settings.favicon_clear': 'Padrão',
    'settings.default_btn': 'Padrão',
    'settings.show_logo': 'Mostrar Logótipo',
    'settings.show_logo_desc': 'Mostrar a imagem do logótipo no cabeçalho e rodapé',
    'settings.show_name': 'Mostrar Nome do Restaurante',
    'settings.show_name_desc': 'Mostrar o texto do nome do restaurante ao lado ou em vez do logótipo',
    'settings.hero': 'URL da Imagem Principal',
    'settings.hero_overlay': 'Sobreposição Principal',
    'settings.intensity': 'Intensidade',
    'settings.bin': 'Reciclagem',
    'settings.bin_empty': 'A sua reciclagem está vazia',
    'settings.data_history': 'Histórico de Dados',
    'settings.all_data': 'Todos os Dados',
    'settings.data_history_access': 'Acesso ao Histórico de Dados',
    'settings.data_history_access_desc': 'Por favor, introduza a palavra-passe do Histórico de Dados para aceder aos registos eliminados permanentemente.',
    'settings.enter_password': 'Introduzir palavra-passe',
    'settings.access': 'Aceder',
    'settings.back_to_bin': 'Voltar à Reciclagem',
    'settings.allow_online': 'Permitir Reservas Online',
    'settings.phone_verification': 'Verificação de Telefone por SMS',
    'settings.phone_verification_desc': 'Exigir que os clientes verifiquem o seu número de telefone via código OTP por SMS usando o Twilio antes de concluir uma reserva online. Certifique-se de que as credenciais do Twilio estão corretas abaixo.',
    'settings.allow_online_desc': 'Se desativado, os clientes verão uma mensagem para ligar em vez do formulário de reserva.',
    'settings.max_online_guests': 'Máximo de Clientes para Reserva Online',
    'settings.max_online_guests_desc': 'O número máximo de pessoas que um cliente pode reservar online. Para grupos maiores, será solicitado que entrem em contacto.',
    'settings.max_months_ahead': 'Período de Reserva Online (Meses)',
    'settings.max_months_ahead_desc': 'Com quanta antecedência em meses os clientes podem reservar online (ex: 1, 2, 3 meses).',
    'settings.show_insights': 'Mostrar Estatísticas de Clientes',
    'settings.show_insights_desc': 'Ativa uma página detalhada com estatísticas de visitas de clientes para administradores.',
    'settings.cloudinary': 'Configuração Cloudinary',
    'settings.cloudinary_cloud_name': 'Cloud Name',
    'settings.cloudinary_api_key': 'API Key',
    'settings.cloudinary_api_secret': 'API Secret',
    'settings.cloudinary_upload_preset': 'Upload Preset',
    'settings.use_cloudinary': 'Usar Cloudinary',
    'settings.use_cloudinary_desc': 'Se ativado, a aplicação dará prioridade às imagens do Cloudinary.',
    'settings.upload_to_cloudinary': 'Carregar para Cloudinary',
    'settings.seo': 'SEO do Restaurante',
    'settings.seo_desc': 'Melhore como o seu restaurante aparece no Google e noutros motores de busca.',
    'settings.seo_health_score': 'Pontuação de Saúde SEO',
    'settings.seo_sync_details': 'Preencher com Dados do Restaurante',
    'settings.seo_sync_success': 'Campos de SEO preenchidos com os dados do perfil do restaurante!',
    'settings.seo_basic_title': 'Informação Básica de SEO',
    'settings.seo_basic_desc': 'O título e a meta descrição principais apresentados nas páginas de resultados dos motores de busca (SERPs).',
    'settings.seo_title': 'Título SEO',
    'settings.seo_title_desc': 'O título mostrado pelos motores de busca para a página do seu restaurante.',
    'settings.seo_title_placeholder': 'Nome do Restaurante | Tipo de Cozinha | Cidade',
    'settings.seo_meta_desc': 'Meta Descrição',
    'settings.seo_meta_desc_desc': 'Uma breve descrição que aparece nos resultados de pesquisa por baixo do título.',
    'settings.seo_meta_desc_placeholder': 'Desfrute de uma experiência gastronómica inesquecível com sabores autênticos e serviço de excelência. Reserve a sua mesa online.',
    'settings.seo_keywords': 'Palavras-chave / Termos de Pesquisa',
    'settings.seo_keywords_desc': 'Palavras-chave ou expressões separadas por vírgulas relacionadas com o seu restaurante.',
    'settings.seo_keywords_placeholder': 'restaurante, marisco, comida tradicional, esplanada, nome da cidade',
    'settings.seo_site_name': 'Nome do Website / Marca (og:site_name)',
    'settings.seo_site_name_desc': 'O nome do website ou da marca apresentado nas tags OpenGraph (por defeito o nome do restaurante).',
    'settings.seo_site_name_placeholder': 'ex.: Restaurante Bella Vista',
    'settings.seo_og_url': 'URL Canónico / Open Graph (og:url)',
    'settings.seo_og_url_desc': 'O URL canónico principal para indexação nos motores de busca e partilha de links.',
    'settings.seo_og_url_placeholder': 'https://o-seu-dominio-restaurante.com/',
    'settings.seo_local_title': 'SEO Local e Rich Snippets',
    'settings.seo_local_desc': 'Informações detalhadas do negócio que ajudam o Google a exibir o seu restaurante em mapas locais e cartões destacados.',
    'settings.seo_cuisine_type': 'Tipo de Cozinha / Restaurante',
    'settings.seo_cuisine_placeholder': 'ex.: Tradicional Portuguesa, Marisqueira, Mediterrânica, Grelhados',
    'settings.seo_price_range': 'Faixa de Preço',
    'settings.seo_city': 'Cidade / Localidade',
    'settings.seo_state': 'Distrito / Região / Concelho',
    'settings.seo_postal_code': 'Código Postal',
    'settings.seo_country': 'País',
    'settings.seo_address': 'Morada para SEO',
    'settings.seo_google_business': 'URL do Perfil Google Negócios',
    'settings.seo_google_maps': 'URL do Google Maps',
    'settings.seo_latitude': 'Latitude',
    'settings.seo_longitude': 'Longitude',
    'settings.seo_geo_hint': 'As coordenadas ajudam os motores de busca a localizar com precisão o restaurante nos mapas.',
    'settings.seo_social_title': 'Partilha nas Redes Sociais (Open Graph e Twitter)',
    'settings.seo_social_desc': 'Controle a aparência do link do seu restaurante quando partilhado no WhatsApp, Facebook, Instagram, LinkedIn e Twitter/X.',
    'settings.seo_social_share_title': 'Título para Redes Sociais',
    'settings.seo_social_share_title_hint': 'Deixe em branco para usar automaticamente o Título SEO',
    'settings.seo_social_share_desc': 'Descrição para Redes Sociais',
    'settings.seo_social_share_desc_hint': 'Deixe em branco para usar automaticamente a Meta Descrição',
    'settings.seo_social_image': 'Imagem de Partilha Social (1200 × 630 px)',
    'settings.seo_social_image_desc': 'Proporção recomendada de 1.91:1 (1200x630px). Insira um URL manual ou envie para o Cloudinary. Se nenhum URL for indicado, nenhuma imagem será exibida nas pré-visualizações sociais.',
    'settings.seo_social_image_clear': 'Limpar Imagem',
    'settings.seo_social_no_image': 'Nenhuma imagem de partilha definida. Nenhuma imagem será exibida ao partilhar links.',
    'settings.seo_social_image_active': 'Imagem de Partilha Ativa',
    'settings.seo_social_image_none': 'Sem Imagem (Cartão Apenas de Texto)',
    'settings.seo_preview_title': 'Pré-visualização nos Motores de Busca e Redes',
    'settings.seo_google_preview': 'Pré-visualização no Google Search',
    'settings.seo_social_preview': 'Pré-visualização nas Redes Sociais',
    'settings.seo_social_box_bg_color': 'Cor de Fundo da Caixa de Pré-visualização',
    'settings.seo_social_box_bg_color_desc': 'Personalize a cor de fundo da caixa inferior neste simulador de partilha.',
    'settings.seo_social_box_bg_disclaimer': 'Apenas Pré-visualização no Painel: Esta é apenas uma preferência de design para o simulador. As plataformas externas (WhatsApp, Facebook, Twitter/X, etc.) apresentam os links com o seu próprio estilo e esquemas de cores nativos.',
    'settings.seo_social_box_bg_reset': 'Repor Fundo da Caixa',
    'settings.seo_social_box_bg_custom': 'Cor Personalizada',
    'settings.seo_social_box_bg_default': 'Estilo Padrão do Sistema',
    'settings.seo_desktop_view': 'Computador',
    'settings.seo_mobile_view': 'Telemóvel',
    'settings.seo_recommendations': 'Recomendações Práticas de SEO',
    'settings.seo_advanced_title': 'Indexação e Dados Estruturados',
    'settings.seo_indexing_toggle': 'Permitir que os motores de busca indexem este site',
    'settings.seo_indexing_on_desc': 'Os motores de busca (Google, Bing, etc.) têm permissão para indexar e classificar as suas páginas.',
    'settings.seo_indexing_off_desc': '⚠️ A etiqueta "noindex, nofollow" será aplicada. A página do restaurante será ocultada dos motores de busca.',
    'settings.seo_canonical_url': 'URL Canónico Personalizado',
    'settings.seo_canonical_desc': 'Indique o URL preferido para esta página para evitar conteúdos duplicados. Gerado automaticamente se vazio.',
    'settings.seo_jsonld_title': 'Dados Estruturados do Restaurante (Schema.org JSON-LD)',
    'settings.seo_jsonld_desc': 'Dados legíveis por máquina gerados automaticamente que ajudam o Google a criar rich cards, horários de funcionamento e ações de reserva.',
    'settings.seo_copy_jsonld': 'Copiar JSON-LD',
    'settings.seo_jsonld_copied': 'JSON-LD copiado para a área de transferência!',
    'settings.seo_test_rich_results': 'Testar com Google Rich Results',
    'settings.resend_api': 'Configuração API Resend',
    'settings.resend_api_key': 'Chave API Resend',
    'settings.resend_api_desc': 'Use o Resend para enviar e-mails transacionais aos seus clientes.',
    'settings.resend_from_email': 'E-mail de Envio do Resend',
    'settings.resend_from_email_desc': 'O endereço de e-mail de envio verificado na sua conta Resend (padrão: "onboarding@resend.dev"). NOTA: Ao usar onboarding@resend.dev, só pode enviar e-mails para o seu próprio endereço de e-mail registado no Resend. Para enviar para outros e-mails, deve verificar o seu domínio no Resend e introduzir o e-mail de envio verificado aqui.',
    'settings.firebase_config': 'Configuração Firebase',
    'settings.firebase_api_key': 'Chave API',
    'settings.firebase_auth_domain': 'Domínio de Autenticação',
    'settings.firebase_project_id': 'ID do Projeto',
    'settings.firebase_storage_bucket': 'Storage Bucket',
    'settings.firebase_messaging_sender_id': 'ID do Remetente de Mensagens',
    'settings.firebase_app_id': 'ID da App',
    'settings.firebase_measurement_id': 'ID de Medição',
    'settings.firebase_database_id': 'ID da Base de Dados (opcional)',
    'settings.firebase_desc': 'Configure um projeto Firebase personalizado para alojar os seus dados ao implementar fora deste ambiente.',
    'settings.twilio_config': 'Configuração Twilio',
    'settings.twilio_account_sid': 'Twilio Account SID',
    'settings.twilio_auth_token': 'Twilio Auth Token',
    'settings.twilio_phone_number': 'Twilio Phone Number',
    'settings.twilio_desc': 'Configure a sua conta Twilio para enviar códigos de verificação reais por SMS para a segurança das reservas. Se não estiver configurado, a aplicação utilizará mensagens simuladas no console.',
    'settings.call_now': 'Ligue agora para reservar uma mesa',
    'settings.call_only_desc': 'Atualmente só aceitamos reservas por telefone. Por favor, contacte-nos diretamente para garantir a sua mesa.',
    'settings.interval': 'Intervalo de Reserva (min)',
    'settings.interval_desc': 'Este intervalo aplica-se a todos os horários de funcionamento padrão.',
    'settings.freeze_app': 'Congelar App (Auto-Bloqueio)',
    'settings.freeze_desc': 'Quando ativado, a aplicação será bloqueada após um período de inatividade. Útil para tablets partilhados ou segurança na recepção.',
    'settings.freeze_pass': 'Senha de Descongelamento',
    'settings.freeze_time': 'Tempo de Inatividade (minutos)',
    'settings.freeze_on': 'Congelamento Ativado',
    'settings.min_gap': 'Intervalo Mín. entre Reservas (min)',
    'settings.min_gap_desc': 'Tempo mínimo necessário entre reservas na mesma mesa.',
    'settings.default_gap': 'Intervalo Padrão',
    'login.title': 'Bem-vindo de volta',
    'login.desc': 'Escolha como deseja iniciar sessão na sua conta.',
    'login.staff': 'Login de Equipa',
    'login.staff_desc': 'Aceda ao painel e gira o restaurante.',
    'login.customer': 'Login de Cliente',
    'login.customer_desc': 'Gira as suas reservas e perfil.',
    'login.signup_title': 'Criar Conta',
    'login.signup_desc': 'Registe-se para gerir as suas reservas e receber ofertas exclusivas.',
    'login.google': 'Entrar com o Google',
    'login.google_signup': 'Registar com o Google',
    'login.no_account': 'Não tem conta? Registe-se',
    'login.have_account': 'Já tem conta? Entre aqui',
    'settings.special_days': 'Configuração de Dias Especiais',
    'settings.add_special': 'Adicionar Dia Especial',
    'settings.footer': 'URL da Imagem do Rodapé',
    'settings.footer_overlay': 'Sobreposição do Rodapé',
    'settings.hours': 'Horário de Funcionamento',
    'settings.social': 'Links de Redes Sociais',
    'settings.add_social': 'Adicionar Link Social',
    'settings.platform': 'Plataforma',
    'settings.url': 'URL',
    'settings.closed': 'Fechado',
    'settings.open': 'Abertura',
    'settings.close': 'Fecho',
    'settings.closed_days': 'Dias de Encerramento',
    'settings.specific_closed': 'Dias de Encerramento Específicos (Feriados, etc.)',
    'settings.closed_periods': 'Períodos de Encerramento (Férias, etc.)',
    'settings.add_period': 'Adicionar Período',
    'settings.start_date': 'Data de Início',
    'settings.end_date': 'Data de Fim',
    'settings.period_note': 'Nota (Ex: Férias de Páscoa)',
    'settings.recurring_yearly': 'Marcar como Permanente (Recorrente Anualmente)',
    'settings.message_popup': 'Popup de Mensagem',
    'settings.promo_active': 'Ativo',
    'settings.promo_start': 'Data de Início',
    'settings.promo_end': 'Data de Fim',
    'settings.promo_title': 'Título',
    'settings.promo_subtitle': 'Subtítulo',
    'settings.promo_message': 'Mensagem',
    'settings.tripadvisor_widget': 'Widget de Avaliações do TripAdvisor',
    'settings.tripadvisor_desc': 'Cole o código do widget do TripAdvisor abaixo',
    'settings.tripadvisor_note': 'Nota: Este widget será exibido na página pública "Reservar uma Mesa".',
    'settings.google_maps_widget': 'Widget do Google Maps',
    'settings.google_maps_desc': 'Cole o código de incorporação do Google Maps abaixo',
    'settings.google_maps_note': 'Nota: Este widget será exibido no rodapé da página pública "Reservar uma Mesa".',
    'dashboard.welcome': 'Bem-vindo de volta! Aqui está o que está a acontecer hoje.',
    'dashboard.welcome_back': 'Bem-vindo de volta,',
    'dashboard.welcome_today': ' Aqui está o que está a acontecer hoje.',
    'dashboard.manage_bookings_desc': 'Veja e gira as suas reservas futuras e passadas.',
    'dashboard.past_cancelled': 'Reservas Passadas e Canceladas',
    'dashboard.today_res': 'Reservas de Hoje',
    'dashboard.pending': 'Pedidos Pendentes',
    'dashboard.available_tables': 'Mesas Disponíveis',
    'dashboard.quick_actions': 'Ações Rápidas',
    'dashboard.live_status': 'Estado da planta em tempo real',
    'dashboard.upcoming': 'Próximas e Ativas',
    'dashboard.legend': 'Legenda',
    'dashboard.upcoming_reports': 'Reservas Futuras',
    'dashboard.upcoming_reports_desc': 'Resumo interativo de reservas futuras por data',
    'dashboard.no_upcoming_reports': 'Sem reservas futuras para reportar.',
    'dashboard.reset_hidden': 'Repor Ocultados',
    'dashboard.show_hidden': 'Mostrar Datas Ocultadas',
    'dashboard.remove_report_confirm': 'Tem a certeza que deseja remover este relatório de reservas desta secção? Isto não irá cancelar as reservas reais.',
    'settings.show_live_upcoming': 'Lista de Próximos e Ativos',
    'settings.show_live_upcoming_desc': 'Mostrar reservas do serviço atual na Visualização ao Vivo',
    'settings.show_lang_switch': 'Mostrar Botão de Idioma',
    'settings.show_lang_switch_desc': 'Mostrar seletor de idioma PT/EN na barra de navegação',
    'settings.silent_bell': 'Silenciar Sino (Notificações)',
    'settings.silent_bell_desc': 'Silenciar o aviso sonoro quando chega uma nova reserva pública',
    'settings.description_pt': 'Descrição (PT)',
    'settings.description_en': 'Descrição (EN)',
    'settings.time_format': 'Formato de Hora',
    'settings.time_format_desc': 'Escolha como a hora é exibida na aplicação (formato AM/PM ou 24 horas).',
    'settings.floor_plan_title': 'Fundo do Desenho da Planta',
    'settings.floor_plan_show': 'Mostrar Imagem de Fundo da Planta',
    'settings.floor_plan_show_desc': 'Exibe um desenho/layout da sua sala por trás das mesas.',
    'settings.floor_plan_url': 'URL da Imagem da Planta',
    'settings.floor_plan_url_desc': 'Forneça um URL para a imagem de fundo da planta ou deixe em branco para usar o Nortada Sala Plan padrão.',
    'settings.floor_plan_opacity': 'Intensidade da Camada de Sobreposição da Planta',
    'settings.floor_plan_bg_type': 'Origem do Fundo',
    'settings.floor_plan_bg_type_desc': 'Escolha se deseja exibir a planta personalizada carregada ou o layout de sala padrão.',
    'settings.floor_plan_use_default': 'Usar Layout de Sala Padrão',
    'settings.floor_plan_use_custom': 'Usar Fundo de Planta Personalizado',
    'res.auto_assign': 'Atribuir Mesa Automaticamente',
    'res.no_table_assign': 'Sem Atribuição de Mesa',
    'public.book_title': 'Reserve a sua Mesa',
    'public.login_manage': 'Registe-se ou faça Login para gerir as suas reservas! ou Reserve como convidado',
    'public.book_desc': 'Experimente a melhor gastronomia. Reserve o seu lugar hoje.',
    'public.hero_subtitle': 'Experimente a melhor gastronomia. Reserve o seu lugar hoje.',
    'public.experience_fine_dining': 'Experimente a alta cozinha no seu melhor. Reserve o seu lugar hoje, no {name}.',
    'public.reviews_tripadvisor': 'O que os nossos clientes dizem no TripAdvisor',
    'public.select_date': 'Selecione Data',
    'public.guest_info': 'Informações do Cliente',
    'public.confirm_booking': 'Confirmar Reserva',
    'public.success_title': 'Reserva Confirmada!',
    'public.success_desc': 'Estamos ansiosos por recebê-lo.',
    'public.closed_message': 'Estamos fechados neste dia. Por favor, selecione outra data.',
    'public.closed_period_message': 'Estamos fechados para {reason}. Estaremos de volta a {date}.',
    'public.back_on': 'De volta a',
    'public.large_group_note': 'Para reservas acima de {max} pessoas, por favor contacte-nos diretamente para verificar disponibilidade.',
    'auth.logged_in_as': 'Sessão iniciada como',
    'auth.login_success': 'Sessão iniciada com sucesso',
    'auth.logged_out': 'Sessão terminada com sucesso',
    'auth.login_error': 'Erro ao iniciar sessão',
    'auth.invalid_credentials': 'E-mail ou senha incorretos. Por favor, tente novamente.',
    'auth.email_in_use': 'Este e-mail já está registado. Por favor, tente iniciar sessão.',
    'auth.logout_error': 'Erro ao terminar sessão',
    'auth.verify_email_sent': 'E-mail de verificação enviado! Por favor, verifique a sua caixa de entrada.',
    'auth.verify_email_first': 'Por favor, verifique o seu e-mail antes de iniciar sessão.',
    'common.all_rights_reserved': 'Todos os direitos reservados.',
    'common.privacy_policy': 'Política de Privacidade',
    'common.terms_conditions': 'Termos & Condições',
    'common.cookie_policy': 'Política de Cookies',
    'common.quick_links': 'Links Rápidos',
    'common.opening_hours': 'Horário de Funcionamento',
    'common.open': 'Aberto',
    'common.close': 'Fechar',
    'common.to': 'a',
    'common.closed': 'Fechado',
    'common.saving': 'A guardar...',
    'common.save_success': 'Definições guardadas com sucesso!',
    'common.save_error': 'Erro ao guardar as definições.',
    'common.cookie_consent': 'Utilizamos cookies para melhorar a sua experiência no nosso website.',
    'common.cookie_accept': 'Aceitar',
    'common.cookie_decline': 'Recusar',
    'common.access_denied': 'Acesso Negado.',
    'common.account_suspended': 'A sua conta encontra-se de momento indisponível.',
    'common.you': 'Você',
    'common.address': 'Morada',
    'common.localization': 'Localização',
    'common.no_messages': 'Nenhuma mensagem criada ainda.',
    'common.create_first': 'Crie a sua primeira mensagem',
    'common.image_url': 'URL da Imagem',
    'common.yearly_recurring': 'Recorrente Anualmente',
    'common.general_hours': 'Horário Geral',
    'common.start_date': 'Data de Início',
    'common.end_date': 'Data de Fim',
    'res.full_house_on': 'Casa Cheia ATIVADO',
    'res.full_house_off': 'Casa Cheia DESATIVADO',
    'res.full_house_msg_active': 'Modo Casa Cheia Ativo para esta Data',
    'res.full_house_msg_deactive': 'Modo Casa Cheia Desativado para esta Data',
    'res.full_house_lunch_active': 'Modo Casa Cheia Ativo para Almoço',
    'res.full_house_lunch_deactive': 'Modo Casa Cheia Desativado para Almoço',
    'res.full_house_dinner_active': 'Modo Casa Cheia Ativo para Jantar',
    'res.full_house_dinner_deactive': 'Modo Casa Cheia Desativado para Jantar',
    'res.lunch_full': 'ALMOÇO CHEIO',
    'res.lunch_open': 'ALMOÇO ABERTO',
    'res.dinner_full': 'JANTAR CHEIO',
    'res.dinner_open': 'JANTAR ABERTO',
    'dashboard.manage_customers': 'Visualize e gira a sua base de dados de clientes.',
    'dashboard.manage_staff': 'Gira o acesso e as funções da equipa.',
    'dashboard.floor_plan': 'Arraste e solte as mesas para organizar o layout do seu restaurante.',
    'res.add_table_hint': 'Clique em "Adicionar Mesa" para começar a construir a sua planta.',
    'res.no_tables': 'Nenhuma mesa adicionada ainda.',
    'res.available': 'Disponível',
    'res.reserved': 'Reservada',
    'res.occupied': 'Ocupada',
    'res.conflict_title': 'Conflito de Horário!',
    'res.conflict_desc': 'Esta atribuição sobrepõe-se a uma reserva existente de {name} às {time}. O intervalo necessário entre reservas é de {gap}.',
    'res.assign_anyway': 'Atribuir de Qualquer Forma',
    'res.manage_seatings': 'Gerir Lugares',
    'res.mark_fully_booked': 'Marcar como Totalmente Reservado',
    'res.seating': 'Lugar',
    'res.add_second_seating': 'Adicionar Segundo Lugar (Cálculo Automático)',
    'res.done': 'Concluído',
    'res.change_time': 'Alterar Hora',
    'res.walkin': 'Entrada Rápida',
    'res.walkin_confirm': 'Confirmar Entrada',
    'res.set_now': 'Definir Agora',
    'tables.join': 'Juntar Mesas',
    'tables.join_desc': 'Selecione as mesas para juntar lado a lado.',
    'tables.total_seats': 'Total de Lugares ao Juntar',
    'tables.unjoin': 'Separar Todas',
    'res.waitlist': 'Lista de Espera',
    'res.show_waitlist': 'Lista de Espera',
    'res.full_house': 'Sem disponibilidade para reservas online',
    'res.full_house_desc': 'De momento não podemos aceitar mais reservas online. Por favor, contacte-nos diretamente para verificar a disponibilidade.',
    'days.monday': 'Segunda-feira',
    'days.tuesday': 'Terça-feira',
    'days.wednesday': 'Quarta-feira',
    'days.thursday': 'Quinta-feira',
    'days.friday': 'Sexta-feira',
    'days.saturday': 'Sábado',
    'days.sunday': 'Domingo',
    'days.mon': 'Seg',
    'days.tue': 'Ter',
    'days.wed': 'Qua',
    'days.thu': 'Qui',
    'days.fri': 'Sex',
    'days.sat': 'Sáb',
    'days.sun': 'Dom',
    'captcha.verify': 'Não sou um robô',
    'captcha.required': 'Por favor, confirme que não é um robô.',
    'captcha.robot_alert': 'Por favor, complete a verificação antes de reservar.',
    'captcha.loading': 'A verificar...',
    'settings.grace_period': 'Período de Tolerância de Reserva (Minutos)',
    'settings.grace_period_desc': 'Especifique o tempo de tolerância (em minutos) permitido para atrasos de clientes antes de a reserva ser considerada expirada e a mesa ser libertada.',
    'settings.enable_booking_number': 'Gerar Número de Reserva Único',
    'settings.enable_booking_number_desc': 'Gerar um código de reserva único (ex: RES-2026-00001) para cada nova reserva.',
    'notfound.badge': 'Erro 404',
    'notfound.title': 'Página Não Encontrada',
    'notfound.desc': 'A página que procura não existe, foi removida ou o endereço está incorreto.',
    'notfound.back_home': 'Voltar ao Início',
    'notfound.book_table': 'Reservar Mesa',
    'notfound.go_back': 'Voltar Atrás',
    'notfound.admin_dashboard': 'Painel de Administração',
    'notfound.my_bookings': 'Minhas Reservas',
    'notfound.need_help': 'Precisa de ajuda?',
    'notfound.contact_us': 'Contacte-nos diretamente',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'pt' ? 'pt-PT' : 'en';
    }
  }, [language]);

  const t = React.useCallback((key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
