import { APP_CONFIG } from './data/appConfig';

export const DAYS_OF_WEEK = [
  'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'
];

export const DEFAULT_SETTINGS = {
  name: APP_CONFIG.appName,
  timezone: 'Europe/Lisbon',
  autoSendManualReservationsEmails: false,
  description: APP_CONFIG.description,
  descriptionEn: APP_CONFIG.description,
  address: APP_CONFIG.address,
  email: APP_CONFIG.email,
  phone: APP_CONFIG.phone,
  websiteUrl: 'https://dinemaster.com',
  heroOverlay: '#000000',
  heroOverlayOpacity: 0.5,
  footerOverlay: '#000000',
  footerOverlayOpacity: 0.7,
  openingHours: DAYS_OF_WEEK.reduce((acc, day) => ({
    ...acc,
    [day]: { 
      open: '09:00', 
      close: '22:00', 
      closed: false,
      lunch: { open: '12:00', close: '15:00', active: false },
      dinner: { open: '19:00', close: '23:00', active: false }
    }
  }), {}),
  closedDays: [],
  showCustomerInsights: false,
  showLogo: true,
  showRestaurantName: true,
  faviconUrl: '',
  cloudinaryFaviconUrl: '',
  fullHouseDates: [],
  fullHouseLunchDates: [],
  fullHouseDinnerDates: [],
  tripadvisorWidget: '',
  showTripadvisorWidget: false,
  googleMapsWidget: '',
  showGoogleMapsWidget: false,
  fontFamily: 'Inter',
  theme: 'light',
  preloaderBg: 'white',
  maxOnlineGuests: 10,
  maxMonthsAhead: 2,
  showFloorPlanBg: true,
  floorPlanBgUrl: '',
  useDefaultFloorPlanBg: false,
  floorPlanOpacity: 1.0,
  silentBell: false,
  phoneVerificationEnabled: false,
  gracePeriod: 15,
  enableBookingNumber: true,
  developingModeEnabled: false,
  developingPassword: '',
  region: 'portugal',
  seo: {
    seoTitle: '',
    seoTitleEn: '',
    seoTitlePt: '',
    metaDescription: '',
    metaDescriptionEn: '',
    metaDescriptionPt: '',
    keywords: '',
    keywordsPt: '',
    cuisineType: 'Contemporary / Traditional',
    priceRange: '€€',
    city: '',
    stateCounty: '',
    postalCode: '',
    country: 'Portugal',
    streetAddress: '',
    googleBusinessUrl: '',
    googleMapsUrl: '',
    latitude: '',
    longitude: '',
    socialTitle: '',
    socialTitlePt: '',
    socialDescription: '',
    socialDescriptionPt: '',
    socialImageUrl: '',
    cloudinarySocialImageUrl: '',
    allowIndexing: true,
    canonicalUrl: ''
  }
};
